### ISSUE TITLE
data4es-nested-atlas-production | 095_datasetInfoAM| Non-JSON AMI response | amiDatasets.py 

### ISSUE THREAD

**Issue by witxka** [PanDAWMS/dkb#434]
**es.atlas-dkb.cern.ch  DKB v0.1-1**
There is a new error in logs /var/log/dkb/data4es-nested-atlas-production.log  to acknowledge. It could be a normal than maybe severity need to be changed to WARNING
```
(95) 2021-02-19 06:27:08 (ERROR) (ProcessorStage) Failed to process dataset 'mc16_13TeV.399012.MGPy8EG_A14NNPDF23LO_StauStau_directLLP_300_0_0p001ns.simul.HITS.e6633_e5984_s3307_tid24250746
_00'
(95) 2021-02-19 06:27:08 (DEBUG) (ProcessorStage) Traceback (most recent call last):
(95) (==)   File "/home/dkb/dkb-test.git/Utils/Dataflow/data4es-nested/run/../095_datasetInfoAMI/amiDatasets.py", line 160, in process
(95) (==)     amiPhysValues(ds)
(95) (==)   File "/home/dkb/dkb-test.git/Utils/Dataflow/data4es-nested/run/../095_datasetInfoAMI/amiDatasets.py", line 202, in amiPhysValues
(95) (==)     raise Exception("Non-JSON AMI response: %s" % res)
(95) (==) Exception: Non-JSON AMI response: <?xml version="1.0" encoding="UTF-8" ?>
(95) (==) <AMIMessage><error><![CDATA[Could not apply converter `AMIXmlToJson.xsl`: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog..]]></err
or><executionTime>0.00</executionTime></AMIMessage>
(95) 2021-02-19 06:27:08 (ERROR) (ProcessorStage) Failed to process dataset 'mc16_13TeV.399012.MGPy8EG_A14NNPDF23LO_StauStau_directLLP_300_0_0p001ns.simul.HITS.e6633_e5984_s3307_tid24250847
_00'
(95) 2021-02-19 06:27:08 (DEBUG) (ProcessorStage) Traceback (most recent call last):
(95) (==)   File "/home/dkb/dkb-test.git/Utils/Dataflow/data4es-nested/run/../095_datasetInfoAMI/amiDatasets.py", line 160, in process
(95) (==)     amiPhysValues(ds)
(95) (==)   File "/home/dkb/dkb-test.git/Utils/Dataflow/data4es-nested/run/../095_datasetInfoAMI/amiDatasets.py", line 202, in amiPhysValues
(95) (==)     raise Exception("Non-JSON AMI response: %s" % res)
(95) (==) Exception: Non-JSON AMI response: <?xml version="1.0" encoding="UTF-8" ?>
(95) (==) <AMIMessage><error><![CDATA[Could not apply converter `AMIXmlToJson.xsl`: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog..]]></error><executionTime>0.00</executionTime></AMIMessage>
```

**Comment by mgolosova** [comment]
Hi @witxka,

Seems like it's AMI's (temporary) internal issue indeed: some parser has failed to parse XML to JSON. Now it works fine, both for one of those failed datasets and a dataset for which AMI has some values for us:
```
>>> print ami_client.execute(command=['GetPhysicsParamsForDataset',
...     '--logicalDatasetName=mc16_13TeV.399012.MGPy8EG_A14NNPDF23LO_StauStau_directLLP_300_0_0p001ns.simul.HITS.e6633_e5984_s3307',
...     '-scope=mc16_13TeV'],
...   format='json')
{"AMIMessage" : [{"Result" : [{"rowset" : []}], ...
>>> print ami_client.execute(command=['GetPhysicsParamsForDataset', '--logicalDatasetName=mc16_13TeV.399012.MGPy8EG_A14NNPDF23LO_StauStau_directLLP_300_0_0p001ns.simul.HITS.e6633_e5984_s3307', '-scope=mc16_13TeV'], format='csv')
#AMI RESULT
#ROWSET
#FIELDS

#VALUES

>>> print ami_client.execute(command=['GetPhysicsParamsForDataset',
...     '--logicalDatasetName=mc16_13TeV.361107.PowhegPythia8EvtGen_AZNLOCTEQ6L1_Zmumu.merge.AOD.e3601_s3126_r11165_r10726',
...     '-scope=mc16_13TeV'],
...   format='json')
{"AMIMessage" : [{"Result" : [{"rowset" : ...
>>> print ami_client.execute(command=['GetPhysicsParamsForDataset', '--logicalDatasetName=mc16_13TeV.361107.PowhegPythia8EvtGen_AZNLOCTEQ6L1_Zmumu.merge.AOD.e3601_s3126_r11165_r10726', '-scope=mc16_13TeV'], format='csv')
#AMI RESULT
#ROWSET
#FIELDS
logicalDatasetName;end_time;insert_time;paramName;paramValue;units;physicsGroup;subprocessID;explanation;createdby;modifiedBy
#VALUES
mc16_13TeV.361107.PowhegPythia8EvtGen_AZNLOCTEQ6L1_Zmumu.merge.AOD.e3601_s3126_r11165_r10726;;2019-06-04 14:01:37;crossSection;1.9011E+00;nb;MCGN;0;jobReport value : averaged over files;amiDataUpload;amiDataUpload
mc16_13TeV.361107.PowhegPythia8EvtGen_AZNLOCTEQ6L1_Zmumu.merge.AOD.e3601_s3126_r11165_r10726;;2017-11-14 11:04:50;crossSectionRef;XsecZleptlept60PowPy;;PMG;0;1950.6321,https://twiki.cern.ch/twiki/bin/view/AtlasProtected/CrossSectionHighOrder#Powheg_V_inclusive_high_order_cr;mcfayden;mcfayden
mc16_13TeV.361107.PowhegPythia8EvtGen_AZNLOCTEQ6L1_Zmumu.merge.AOD.e3601_s3126_r11165_r10726;;2017-12-12 17:39:50;crossSectionTotalRelUncertUP;0.05;;SUSY;0;ATLSUSYSW-324:add uncertainty from SUSYTools package;will;will
mc16_13TeV.361107.PowhegPythia8EvtGen_AZNLOCTEQ6L1_Zmumu.merge.AOD.e3601_s3126_r11165_r10726;;2016-10-30 01:12:34;genFiltEff;1.0000E+00;;MCGN;0;jobReport value : averaged over files;amiDataUpload;amiDataUpload
mc16_13TeV.361107.PowhegPythia8EvtGen_AZNLOCTEQ6L1_Zmumu.merge.AOD.e3601_s3126_r11165_r10726;;2017-11-14 11:03:45;kFactor;1.02605444217;;PMG;0;XsecZleptlept60PowPy;mcfayden;mcfayden
mc16_13TeV.361107.PowhegPythia8EvtGen_AZNLOCTEQ6L1_Zmumu.merge.AOD.e3601_s3126_r11165_r10726;;2017-10-03 22:01:47;processGroup;Zjets_PowPy8_incl;;PMG;0;Automatic CentralPage upload;mcfayden;mcfayden
```

Makes sence to turn this into `WARNING`, the only question I have is: **should it be accompanied with some additional info (which is in the `DEBUG` section now)?**

Maybe something like this:
```
(95) 2021-02-19 06:27:08 (WARN) (ProcessorStage) Failed to process dataset 'mc16_13TeV.399012.MGPy8EG_A14NNPDF23LO_StauStau_directLLP_300_0_0p001ns.simul.HITS.e6633_e5984_s3307_tid24250746_00'
(95) (==) Non-JSON AMI response: '''<?xml version="1.0" encoding="UTF-8" ?>\n<AMIMessage><error><![CDATA[Could not apply converter `AMIXmlToJson.xsl`: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog..]]></error><executionTime>0.00</executionTime></AMIMessage>'''
```
?

**Comment by witxka** [comment]
I think it is better to add additional info if it is not very difficult to implement.

**Comment by mgolosova** [comment]
@witxka, OK, will do :)
